"""Add age column to animals table

Revision ID: 595721b76569
Revises: c1f0db8cade7
Create Date: 2025-01-25 16:23:49.064856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595721b76569'
down_revision = 'c1f0db8cade7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('age', sa.Integer(), nullable=True))
    op.alter_column('enclosures', 'environment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('enclosures', 'open_to_visitors',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('zookeepers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('zookeepers', 'birthday',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zookeepers', 'birthday',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('zookeepers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('enclosures', 'open_to_visitors',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('enclosures', 'environment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('animals', 'age')
    # ### end Alembic commands ###
